services:

  postgres:
    image: postgres:16-alpine
    container_name: ecommerce-postgres
    restart: always

    env_file:
      - .env

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ecommerce"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: ecommerce-backend
    restart: always

    env_file:
      - ./backend/.env.docker

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL:  ${REACT_APP_BACKEND_URL}

    container_name: ecommerce-frontend
    restart: always

    depends_on:
      - backend

    ports:
      - "3000:80"

volumes:
  postgres_data:
